@startuml AjoutPage
title "Diagramme de séquence pour l'ajout d'une page" 

actor Utilisateur as U #Purple 
participant Application as A #Yellow 
participant Serveur as S #Green 
participant BDD as Db #Red 

U -> A : Se connecter en tant qu'Admin
A -> S : Authentification 
S -> Db : Vérification des identifiants 
Db --> S : Confirmation des identifiants
S --> A : Authentification réussie
A --> U : Vous êtes connecté en tant qu'Admin
U -> A : Ajouter une page
A -> S : Envoi de la page
S -> Db : Ajout de la page dans la BDD
Db --> S : Confirmation de l'ajout
S --> A : Page ajoutée avec succès
A --> U : Page ajoutée avec succès

@enduml  