@startuml ModificationCategorie
title "Diagramme de séquence pour la modification d'une catégorie"

actor Utilisateur as U #Purple 
participant Application as A #Yellow 
participant Serveur as S #Green 
participant BDD as Db #Red 

U -> A : Se connecter en tant qu'Admin
A -> S : Authentification 
S -> Db : Vérification des identifiants 
Db --> S : Confirmation des identifiants
S --> A : Authentification réussie
A --> U : Vous êtes connecté en tant qu'Admin
U -> A : Afficher les catégories
A -> S : Demande d'affichage des catégories
S -> Db : Récupération des catégories
Db --> S : Renvoi des catégories
S --> A : Catégories récupérées
A --> U : Affichage des catégories
U -> A : Sélectionner une catégorie à modifier
A -> S : Demande de la catégorie à modifier
S -> Db : Récupération de la catégorie
Db --> S : Catégorie récupérée
S --> A : Catégorie récupérée
A --> U : Affichage de la catégorie
U -> A : Modifier une catégorie
A -> S : Envoi de la catégorie modifiée
S -> Db : Modification de la catégorie dans la BDD
Db --> S : Confirmation de la modification
S --> A : Catégorie modifiée avec succès
A --> U : Catégorie modifiée avec succès

@enduml  