@startuml SuppressionPage
title "Diagramme de séquence pour la suppression d'une page"

actor Utilisateur as U #Purple 
participant Application as A #Yellow 
participant Serveur as S #Green 
participant BDD as Db #Red 

U -> A : Se connecter en tant qu'Admin
A -> S : Authentification 
S -> Db : Vérification des identifiants 
Db --> S : Confirmation des identifiants
S --> A : Authentification réussie
A --> U : Vous êtes connecté en tant qu'Admin
U -> A : Afficher la liste des pages
A -> S : Demande de la liste des pages
S -> Db : Récupération de la liste des pages
Db --> S : Renvoi de la liste des pages
S --> A : Liste des pages
A --> U : Affichage de la liste des pages
U -> A : Sélectionner la page à supprimer
A -> S : Envoi de la demande de suppression
S -> Db : Suppression de la page dans la BDD
Db --> S : Confirmation de la suppression
S --> A : Page supprimée avec succès
A --> U : Page supprimée avec succès

@enduml  