services:
  # Database service
  # This service uses the MySQL image and sets up a database for the application
  database:
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3310:3306'
    volumes:
      - database:/var/lib/mysql
    
  # PHPMyAdmin service
  # This service uses the PHPMyAdmin image to provide a web interface for managing the MySQL database
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: database

volumes:
  # Database volume to persist data
  database:
