@startuml UserStoryAuteurArticle

left to right direction
skinparam actorFontStyle bold
skinparam usecase {
    BackgroundColor YellowGreen
    BorderColor Black
}

actor "Auteur" as Au #LightBlue;text:LightBlue

package "Gestion des articles" {
    usecase "Ajouter article" as Aa #LightGray;text:Black
    usecase "Modifier article" as Ma #LightGray;text:Black
    usecase "Supprimer article" as Sa #LightGray;text:Black
}

' Relations entre acteurs et cas d'utilisation
Au --> Aa
Au --> Ma
Au --> Sa

' Description des cas d'utilisation
note right of Aa
    En temps qu'auteur, je peux ajouter un nouvel article.
end note
note right of Ma
    En temps qu'auteur, je peux modifier un article existant.
end note
note right of Sa
    En temps qu'auteur, je peux supprimer un article existant.
end note

@enduml