@startuml AdminDeleteCategorie
title Suppression d'une catégorie par un administrateur

|Admin|
start
:Accès au dashboard;
|Serveur|
if (Utilisateur est connecté et a le role admin ?) then (non)
  |Admin|
  #red: **Message d'erreur**;
  stop
else (oui)
  |Admin|
  :Accès à la section de gestion des catégories;
  :Sélectionner une catégorie;
    :Cliquer sur le bouton de suppression;
  |Serveur|
  :Envoi de la requête de suppression en base de données;
  if () is (si erreur) then
    |Admin|
    #red:**Message d'erreur**;
    stop
  else (si valide)
    |Serveur|
    :Demande de confirmation;
    |Admin|
    :Confirmation de la suppression;
    |Serveur|
    :Suppression de la catégorie en base de données;
    |Admin|
    :Affichage d'un message de succès;
    :Redirection vers la liste des catégories;
    stop
  endif
endif
@enduml